---
apiVersion: v1
kind: Namespace
metadata:
  name: "swiss-army-knife"
  labels:
    app: "swiss-army-knife"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: swiss-army-knife-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: swiss-army-knife
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swiss-army-knife
  name: swiss-army-knife
  namespace: swiss-army-knife
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiss-army-knife
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: swiss-army-knife
    spec:  
      containers:
      - image: rancherlabs/swiss-army-knife
        imagePullPolicy: IfNotPresent
        name: swiss-army-knife
      restartPolicy: Always